apiVersion: v1
kind: Service
metadata:
  name: vetta-api
  namespace: vetta
  labels:
    app.kubernetes.io/name: vetta
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vetta
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
