apiVersion: v1
kind: Secret
metadata:
  name: vetta-secrets
  namespace: vetta
  labels:
    app.kubernetes.io/name: vetta
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://vetta_prod_user:change_in_production@vetta-postgres.vetta.svc.cluster.local:5432/vetta_prod"
  GOOGLE_API_KEY: "change_with_production_gemini_key"
  AWS_ACCESS_KEY_ID: "change_with_production_aws_key"
  AWS_SECRET_ACCESS_KEY: "change_with_production_aws_secret"
